### ISSUE TITLE
java.lang.NoClassDefFoundError exception

### ISSUE THREAD

**Issue by Koshak118** [square/jna-gmp#31]
Hi

Thanks for this great wrapper, first of all

The issue I've been messing around in a last couple of days is the exception mentioned in the subject, which is thrown in runtime. The trivial things like playing dependencies definitions and their scopes in pom.xml did not help, the local maven repositories and paths seem to BE OK  The stack is as the following:
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class ```
com.squareup.jnagmp.LibGmp
	at com.squareup.jnagmp.Gmp.<init>(Gmp.java:175)
	at com.squareup.jnagmp.Gmp.<init>(Gmp.java:33)
	at com.squareup.jnagmp.Gmp$1.initialValue(Gmp.java:133)
	at com.squareup.jnagmp.Gmp$1.initialValue(Gmp.java:131)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.squareup.jnagmp.Gmp.modPowInsecure(Gmp.java:95)
```

```
The relevant pom.xml section:
<dependencies>
		<dependency>
			<groupId>com.squareup.jnagmp</groupId>
			<artifactId>jnagmp</artifactId>
			<version>2.1.0</version>
		</dependency>
..........
		<dependency>
			<groupId>com.squareup.jnagmp</groupId>
			<artifactId>bouncycastle-rsa</artifactId>
			<version>2.1.0</version>
		</dependency>
</dependencies>
```
Any ideas?

Thanks

**Comment by dragonsinth** [comment]
@Koshak118 are you on the latest version?  Those line numbers make no sense based on the current source code I'm looking at.

**Comment by Koshak118** [comment]
Hi @dragonsinth

Sorry for the delayed answer, was with a limited access to the internet for a couple of days

Upgrading the code to the latest version didn't fix a crash; what did fix it is trying to run the code on Mac rather than on Windows, so it looks like it was an environment setup issue

As far as I am concerned you can close the issue

Thanks for the assistance

**Comment by dragonsinth** [comment]
Ah, yes.  We don't provide a pre-built binary libgmp for Windows.  You'd need to build libgmp yourself.
